// Generated by scripts/prepare-city-content.mjs. Edit the source catalogue or editorial files.
export const cityPhotos: Record<string, { heroImage: string; heroImageCredit: string }> = {
  "blagoevgrad": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Blagoevgrad_Panorama_01.jpg/1920px-Blagoevgrad_Panorama_01.jpg",
    "heroImageCredit": "Снимка: Михал Орела, Wikimedia Commons"
  },
  "burgas": {
    "heroImage": "https://upload.wikimedia.org/wikipedia/commons/1/18/View_of_Burgas11.jpg",
    "heroImageCredit": "Снимка: Balkanregion, Wikimedia Commons"
  },
  "gabrovo": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/Gabrovo%2C_Bulgaria_-_panoramio_%288%29.jpg/1920px-Gabrovo%2C_Bulgaria_-_panoramio_%288%29.jpg",
    "heroImageCredit": "Снимка: Красимир Косев, Wikimedia Commons"
  },
  "pleven": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Pleven_Center%2C_Pleven%2C_Bulgaria_-_panoramio.jpg/1920px-Pleven_Center%2C_Pleven%2C_Bulgaria_-_panoramio.jpg",
    "heroImageCredit": "Снимка: Красимир Косев, Wikimedia Commons"
  },
  "plovdiv": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Plovdiv_-_Roman_Amphitheatre_-_panoramio.jpg/1920px-Plovdiv_-_Roman_Amphitheatre_-_panoramio.jpg",
    "heroImageCredit": "Снимка: diego_cue, Wikimedia Commons"
  },
  "ruse": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Ruse_Bulgaria_center.jpg/1920px-Ruse_Bulgaria_center.jpg",
    "heroImageCredit": "Снимка: Commentatora123, Wikimedia Commons"
  },
  "shumen": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Shumen%2C_Bulgaria_-_panoramio_%2810%29.jpg/1920px-Shumen%2C_Bulgaria_-_panoramio_%2810%29.jpg",
    "heroImageCredit": "Снимка: karel291, Wikimedia Commons"
  },
  "sofia": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/A_view_of_Sofia_city_center..JPG/1920px-A_view_of_Sofia_city_center..JPG",
    "heroImageCredit": "Снимка: Rudolphfurtado, Wikimedia Commons (CC0)"
  },
  "stara-zagora": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f2/Stara_zagora_panorama_bg.jpg/1920px-Stara_zagora_panorama_bg.jpg",
    "heroImageCredit": "Снимка: Balkanregion, Wikimedia Commons"
  },
  "svishov": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Svishtov%2C_Bulgaria_2010.jpg/1920px-Svishtov%2C_Bulgaria_2010.jpg",
    "heroImageCredit": "Снимка: Спасимир, Wikimedia Commons"
  },
  "varna": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Varna%2C_Bulgaria_-_panoramio_%2825%29.jpg/1920px-Varna%2C_Bulgaria_-_panoramio_%2825%29.jpg",
    "heroImageCredit": "Снимка: karel291, Wikimedia Commons"
  },
  "veliko-tarnovo": {
    "heroImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/View_over_Fortress_-_Veliko_Tarnovo_-_Bulgaria_%2843199853991%29.jpg/1920px-View_over_Fortress_-_Veliko_Tarnovo_-_Bulgaria_%2843199853991%29.jpg",
    "heroImageCredit": "Снимка: Adam Jones, Wikimedia Commons"
  }
};
