import { useState } from 'react';
import { Link } from 'react-router-dom';
export interface DirectoryCity { slug: string; name: string; region: string; isUniversityCity?: boolean }
export default function CityDirectory({ cities, title, subtitle }: { cities: readonly DirectoryCity[]; title: string; subtitle?: string }) {
  const [query, setQuery] = useState('');
  const normalized = query.trim().toLocaleLowerCase('bg');
  const sorted = [...cities].sort((a, b) => a.name.localeCompare(b.name, 'bg') || a.region.localeCompare(b.region, 'bg'));
  const items = sorted.filter(city => `${city.name} ${city.region}`.toLocaleLowerCase('bg').includes(normalized));
  const regions = [...new Set(sorted.map(city => city.region))].sort((a, b) => a.localeCompare(b, 'bg'));
  const links = (records: DirectoryCity[]) => <ul className="grid gap-x-5 gap-y-1 sm:grid-cols-2 lg:grid-cols-3">{records.map(city => <li key={city.slug}><Link to={`/kvartiri-bez-posrednik/${city.slug}`} className="flex min-h-12 items-center justify-between gap-3 rounded-lg px-3 py-2 text-sm hover:bg-primary-50 hover:text-primary-800"><div><span className="font-medium">{city.name}</span>{normalized && <span className="mt-0.5 block text-xs text-foreground-600">Област {city.region}</span>}</div>{city.isUniversityCity ? <i className="ri-graduation-cap-line text-primary-700" role="img" aria-label="Висше училище или филиал" /> : <i className="ri-arrow-right-s-line text-foreground-500" aria-hidden="true" />}</Link></li>)}</ul>;
  return <section id="vsichki-gradove" tabIndex={-1} className="outline-none"><div className="grid gap-5 md:grid-cols-2 md:items-end"><div><h2 className="font-heading text-2xl font-semibold">{title}</h2>{subtitle && <p className="mt-3 text-sm leading-relaxed text-foreground-600">{subtitle}</p>}</div><label className="ui-label mb-0" htmlFor="directory-search">Намери град или област<input id="directory-search" type="search" value={query} onChange={event => setQuery(event.target.value)} className="ui-field mt-2" placeholder="Например Варна, Враца, Добрич…" /></label></div>
    <p role="status" className="ui-note mt-5">{items.length} града · {regions.length} области · <i className="ri-graduation-cap-line text-primary-700" aria-hidden="true" /> Висше училище или филиал в каталога</p>
    {normalized ? <div className="ui-panel mt-4">{items.length ? links(items) : <p className="text-sm text-foreground-600">Няма съвпадение. Опитай с част от името или с областта.</p>}</div> : <div className="mt-4 grid items-start gap-3 md:grid-cols-2">{regions.map(region => { const records = sorted.filter(city => city.region === region); return <details key={region} id={`oblast-${records[0].slug}`} className="rounded-xl border border-background-200 bg-background-50 px-3"><summary className="flex min-h-14 list-none items-center justify-between gap-3 px-2 py-3 font-medium"><span>Област {region}<span className="ml-2 text-xs font-normal text-foreground-500">{records.length} {records.length === 1 ? 'град' : 'града'}</span></span><i className="ri-add-line text-foreground-500" aria-hidden="true" /></summary><div className="border-t border-background-200 py-3">{links(records)}</div></details>; })}</div>}
  </section>;
}
