// Generated by scripts/prepare-city-content.mjs. Edit the source catalogue or editorial files.
export const editorialSeoIndex = [
  {
    "path": "/saveti/kak-da-razpoznam-broker",
    "title": "Как да разпознаем брокер, който се представя за собственик",
    "description": "Практичен чеклист с червени флагове, подозрителни фрази и проверки преди оглед — за да не платиш комисион, който не дължиш.",
    "ogImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Apartment_Living_Room_1_2018-09-28.jpg/1920px-Apartment_Living_Room_1_2018-09-28.jpg",
    "ogType": "article"
  },
  {
    "path": "/saveti/kvartira-za-studenti",
    "title": "Квартира за студенти: локация, бюджет и как да не изгориш",
    "description": "Как да избереш място спрямо университета, какъв бюджет е реален всеки месец и как да делиш наем със съквартиранти без изненади.",
    "ogImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Female_student_writing_and_studying_at_dorm_room_desk.jpg/1920px-Female_student_writing_and_studying_at_dorm_room_desk.jpg",
    "ogType": "article"
  },
  {
    "path": "/saveti/naemodatel-bez-agencia",
    "title": "Как собственикът да отдаде апартамент сам, без агенция — стъпка по стъпка",
    "description": "Как да подготвиш имота, да напишеш обява, която продава сама, да подбереш наемател и да подпишете договор без посредник.",
    "ogImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Empty_apartment_living_room.jpg/1920px-Empty_apartment_living_room.jpg",
    "ogType": "article"
  },
  {
    "path": "/saveti/ot-ogled-do-dogovor",
    "title": "От оглед до договор: пълен наръчник за наем директно от собственик",
    "description": "Какво да подготвиш преди огледа, какво да гледаш на място, кои документи и клаузи пазят и двете страни и как става предаването на имота.",
    "ogImage": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Lease.jpg",
    "ogType": "article"
  },
  {
    "path": "/saveti/skriti-taksi-i-komisioni",
    "title": "Скритите такси и комисиони при наем — и как да не ги плащаш",
    "description": "Кои разходи са реални, кои са измислени и как да различиш честните условия от такса, която просто няма основание.",
    "ogImage": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Euro_coins_and_banknotes.jpg/1920px-Euro_coins_and_banknotes.jpg",
    "ogType": "article"
  },
  {
    "path": "/kak-raboti",
    "title": "От търсенето до директния разговор",
    "description": "Намери жилище, провери условията и говори с човека, който има право да го отдава. Платформата не приема депозити и не участва в плащанията по наема."
  },
  {
    "path": "/za-nas",
    "title": "Директният наем започва с ясна информация",
    "description": "Квартири без посредник е платформа за връзка между наемодатели и хора, които търсят дом в България. Нашата цел е повече прозрачност при всяка стъпка."
  },
  {
    "path": "/kak-da-razpoznaem-posrednik",
    "title": "Разпознай риска преди огледа",
    "description": "Един съмнителен признак не доказва измама. Няколко несъответствия са причина да спреш, да поискаш пояснение и при нужда да подадеш сигнал."
  }
];
