import CityLocationFields from '@/components/feature/CityLocationFields';
import type { ListingDraft, DraftIssue } from '@/lib/listingDraft';
import type { City, Neighborhood, University, ListingType } from '@/lib/types';
import OwnerPublishingTips from './OwnerPublishingTips';
interface Props { draft: ListingDraft; issue: DraftIssue | null; cities: City[]; neighborhoods: Neighborhood[]; universities: University[]; onChange: <K extends keyof ListingDraft>(key: K, value: ListingDraft[K]) => void }
const types: { value: ListingType; label: string }[] = [{ value: 'apartment', label: 'Апартамент' }, { value: 'room', label: 'Стая' }, { value: 'studio', label: 'Студио' }, { value: 'house', label: 'Къща' }];
export default function ListingDetailsFields({ draft, issue, cities, neighborhoods, universities, onChange }: Props) {
  const input = (key: 'title' | 'price' | 'area' | 'rooms' | 'floor' | 'totalFloors' | 'deposit' | 'availableFrom', label: string, attrs: Record<string, string | number> = {}) => {
    const id = 'nf-' + (key === 'availableFrom' ? 'available' : key === 'totalFloors' ? 'total-floors' : key);
    return <div><label htmlFor={id} className="ui-label">{label}</label><input id={id} className="ui-field" value={draft[key]} aria-invalid={issue?.field === id || undefined} aria-describedby={issue?.field === id ? 'listing-form-error' : undefined} onChange={event => onChange(key, event.target.value)} {...attrs} /></div>;
  };
  return <div className="space-y-5">
    <CityLocationFields id="nf" cities={cities} neighborhoods={neighborhoods} universities={universities} cityValue={draft.cityId} neighborhoodValue={draft.neighborhoodId} universityValues={draft.universityIds} keyMode="id" required multipleUniversities onCityChange={value => { onChange('cityId', value); onChange('neighborhoodId', ''); onChange('universityIds', []); }} onNeighborhoodChange={value => onChange('neighborhoodId', value)} onUniversitiesChange={value => onChange('universityIds', value)} />
    <p className="ui-note">Градът е задължителен. Кварталът и университетите са по желание. Не посочвай точен адрес, телефон или имейл в публичния текст.</p>
    <div className="grid gap-4 sm:grid-cols-2">{input('title', 'Заглавие *', { maxLength: 120, placeholder: 'Например: Светло студио до университета' })}<div><label className="ui-label" htmlFor="nf-type">Тип жилище</label><select className="ui-field" id="nf-type" value={draft.type} onChange={event => onChange('type', event.target.value as ListingType)}>{types.map(type => <option value={type.value} key={type.value}>{type.label}</option>)}</select></div></div>
    <div><label htmlFor="nf-description" className="ui-label">Описание *</label><textarea id="nf-description" className="ui-field h-auto min-h-32 py-3" rows={4} minLength={30} maxLength={5000} aria-invalid={issue?.field === 'nf-description' || undefined} aria-describedby="nf-description-hint" value={draft.description} onChange={event => onChange('description', event.target.value)} placeholder="Разпределение, състояние, транспорт и условия. Без телефон или имейл." /><p id="nf-description-hint" className="ui-note mt-2">{draft.description.length}/5000 · минимум 30 знака</p></div>
    <div className="grid gap-4 sm:grid-cols-2">{input('price', 'Месечен наем (€) *', { type: 'number', min: 0.01, step: 0.01, inputMode: 'decimal' })}{input('area', 'Площ (m²) *', { type: 'number', min: 0.01, step: 0.01, inputMode: 'decimal' })}{input('rooms', 'Брой стаи *', { type: 'number', min: 1, max: 100, step: 1, inputMode: 'numeric' })}{input('availableFrom', 'Свободно от *', { type: 'date' })}</div>
    <OwnerPublishingTips topic="price" citySlug={cities.find(city => city.id === draft.cityId)?.slug} type={draft.type} price={draft.price} area={draft.area} />
    <OwnerPublishingTips topic="timing" />
    <div className="flex flex-wrap gap-3">{([['furnished', 'Обзаведено'], ['pets', 'Домашни любимци'], ['utilities', 'Разходите са включени']] as const).map(([key, label]) => <label key={key} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-background-300 px-3 text-sm"><input type="checkbox" checked={draft[key]} onChange={event => onChange(key, event.target.checked)} />{label}</label>)}</div>
    <details className="rounded-xl border border-background-200 p-4" open={Boolean(issue && ['nf-floor', 'nf-total-floors', 'nf-deposit'].includes(issue.field)) || undefined}><summary className="text-sm font-medium">Етаж и депозит · по желание</summary><div className="mt-4 grid gap-4 sm:grid-cols-3">{input('floor', 'Етаж', { type: 'number', min: -5, max: 200, step: 1 })}{input('totalFloors', 'Етажи в сградата', { type: 'number', min: 1, max: 200, step: 1 })}{input('deposit', 'Депозит (€)', { type: 'number', min: 0, step: 0.01 })}</div></details>
  </div>;
}
