import { Link } from 'react-router-dom';
interface Props { topic: 'price' | 'photos' | 'timing'; citySlug?: string; type?: string; price?: string; area?: string }
export default function OwnerPublishingTips({ topic, citySlug, type, price = '', area = '' }: Props) {
  const heading = topic === 'photos' ? 'Снимки, които показват истинския имот' : topic === 'price' ? 'Как да избереш разумен наем' : 'Кога да публикуваш';
  const perM2 = Number(price) > 0 && Number(area) > 0 && Number.isFinite(Number(price) / Number(area)) ? (Number(price) / Number(area)).toLocaleString('bg-BG', { maximumFractionDigits: 2 }) : '';
  const query = new URLSearchParams(); if (citySlug) query.set('grad', citySlug); if (type) query.set('tip', type);
  return <details className="group rounded-xl border border-background-200 bg-background-100 px-4 py-2 text-sm"><summary className="flex items-center justify-between gap-3 font-medium text-primary-800">{heading}<i className="ri-arrow-down-s-line shrink-0 transition-transform group-open:rotate-180" aria-hidden="true" /></summary>
    {topic === 'photos' ? <ul className="my-3 list-disc space-y-2 pl-5 leading-relaxed text-foreground-700"><li>Подреди, отвори завесите и снимай на дневна светлина. Дръж телефона изправен и използвай обичайния обектив.</li><li>Покажи всяка стая, кухнята и банята. Избери ясна обща снимка за корица; добави и недостатъците, които влияят на избора.</li><li>Използвай свои актуални снимки. Без AI промяна на имота, агресивни филтри и разтягане на пространството.</li><li>Прибери документи, ключове с адрес, лични снимки и вещи с имена. Не включвай хора без съгласие.</li><li>Можеш да започнеш с една снимка. За полезен оглед на обявата добави няколко различни гледни точки.</li></ul>
      : topic === 'price' ? <div className="my-3 space-y-3 leading-relaxed text-foreground-700"><p>Сравни сходни жилища в същия район: площ, състояние, обзавеждане, транспорт и включени разходи. Обявеният наем е искана цена, а не доказана цена по договор.</p><p>Посочи отделно наема и депозита. Уточни сметките и поддръжката; не компенсирай нисък наем със скрити такси.</p>{perM2 && <p className="font-medium text-primary-800">Твоят наем: {perM2} €/m² на месец. Това е изчисление по въведените суми, не пазарна оценка.</p>}<Link to={'/tarsene' + (query.size ? '?' + query.toString() : '')} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-2 font-medium text-primary-800 underline">Сравни наличните обяви (нов раздел)</Link><p className="ui-note">При малко предложения няма достатъчно данни за средна цена. Ако няма подходящ интерес, провери първо снимките и условията, после прецени цената.</p></div>
      : <div className="my-3 space-y-3 leading-relaxed text-foreground-700"><p>Публикувай, когато имаш актуални снимки, ясни условия и реална дата за нанасяне — дори тя да е предстояща. Подготви време за отговори и огледи.</p><p>При студентско жилище провери началото на семестъра на съответния университет. Няма универсален „най-добър час“ за всички градове.</p><p>При промяна редактирай същата обява. Когато намериш наемател, отбележи „Наето“, за да спестиш напразни запитвания.</p></div>}
    <Link to="/saveti/naemodatel-bez-agencia" target="_blank" rel="noopener noreferrer" className="mb-2 inline-flex min-h-11 items-center text-xs font-medium text-primary-800 underline">Целият наръчник за собственици (нов раздел)</Link>
  </details>;
}
