import CityLocationFields from '@/components/feature/CityLocationFields';
import type { City, Neighborhood, University } from '@/lib/types';
export interface SearchFilterValues { citySlug:string; neighborhoodSlug:string; universitySlug:string; type:string; rooms:string; priceMin:string; priceMax:string; areaMin:string; areaMax:string; floorMin:string; floorMax:string; furnished:string; pets:string; availableFrom:string; text:string }
interface Props { cities:City[]; neighborhoods:Neighborhood[]; universities:University[]; values:SearchFilterValues; onChange:(field:keyof SearchFilterValues,value:string)=>void; onReset:()=>void; onApply:()=>void }
export default function SearchFilters({ cities, neighborhoods, universities, values, onChange, onReset, onApply }: Props) {
  const rooms=values.rooms.split(',').filter(Boolean);
  const toggle=(value:string)=>onChange('rooms',rooms.includes(value)?rooms.filter(item=>item!==value).join(','):[...rooms,value].join(','));
  const range=(label:string,min:keyof SearchFilterValues,max:keyof SearchFilterValues,integer=false)=><fieldset><legend className="ui-label">{label}</legend><div className="grid grid-cols-2 gap-2"><input type="number" min={integer?-5:0} step={integer?1:'any'} value={values[min]} onChange={event=>onChange(min,event.target.value)} aria-label={label+' от'} placeholder="От" className="ui-field" /><input type="number" min={integer?-5:0} step={integer?1:'any'} value={values[max]} onChange={event=>onChange(max,event.target.value)} aria-label={label+' до'} placeholder="До" className="ui-field" /></div></fieldset>;
  const moreCount=['areaMin','areaMax','floorMin','floorMax','furnished','pets','availableFrom','text'].filter(key=>Boolean(values[key as keyof SearchFilterValues])).length;
  return <form onSubmit={event=>{event.preventDefault();onApply();}} className="ui-panel">
    <div className="mb-5 flex items-center justify-between gap-3"><h2 className="font-heading font-semibold">Филтри</h2><button type="button" onClick={onReset} className="text-xs font-medium text-foreground-600 hover:text-primary-700">Изчисти</button></div>
    <div className="space-y-5"><CityLocationFields compact id="f" cities={cities} neighborhoods={neighborhoods} universities={universities} cityValue={values.citySlug} neighborhoodValue={values.neighborhoodSlug} universityValues={values.universitySlug?[values.universitySlug]:[]} onCityChange={value=>onChange('citySlug',value)} onNeighborhoodChange={value=>onChange('neighborhoodSlug',value)} onUniversitiesChange={value=>onChange('universitySlug',value[0]??'')} />
      <div><label htmlFor="f-type" className="ui-label">Тип жилище</label><select id="f-type" value={values.type} onChange={event=>onChange('type',event.target.value)} className="ui-field"><option value="all">Всички типове</option><option value="apartment">Апартамент</option><option value="room">Стая</option><option value="studio">Студио</option><option value="house">Къща</option></select></div>
      {range('Месечен наем (€)','priceMin','priceMax')}
      <fieldset><legend className="ui-label">Стаи</legend><div className="grid grid-cols-4 gap-2">{['1','2','3','4+'].map(value=><button type="button" key={value} aria-pressed={rooms.includes(value)} onClick={()=>toggle(value)} className={'min-h-11 rounded-lg border text-sm '+(rooms.includes(value)?'border-primary-500 bg-primary-50 text-primary-800':'border-background-300')}>{value}</button>)}</div></fieldset>
      <details open={moreCount>0||undefined} className="border-t border-background-200 pt-3"><summary className="flex items-center justify-between text-sm font-medium">Още филтри{moreCount>0&&<span className="text-xs text-primary-700">{moreCount} избрани</span>}</summary><div className="mt-4 space-y-5">
        {range('Площ (m²)','areaMin','areaMax')}{range('Етаж','floorMin','floorMax',true)}
        <div><label className="ui-label" htmlFor="f-furnished">Обзавеждане</label><select id="f-furnished" value={values.furnished} onChange={event=>onChange('furnished',event.target.value)} className="ui-field"><option value="">Без предпочитание</option><option value="1">Обзаведено</option><option value="0">Необзаведено</option></select></div>
        <div><label className="ui-label" htmlFor="f-pets">Домашни любимци</label><select id="f-pets" value={values.pets} onChange={event=>onChange('pets',event.target.value)} className="ui-field"><option value="">Без предпочитание</option><option value="1">Позволени</option><option value="0">Непозволени</option></select></div>
        <div><label className="ui-label" htmlFor="f-available">Свободно до дата</label><input type="date" id="f-available" value={values.availableFrom} onChange={event=>onChange('availableFrom',event.target.value)} className="ui-field" /></div>
        <div><label className="ui-label" htmlFor="f-keyword">Дума в обявата</label><input type="search" id="f-keyword" maxLength={200} value={values.text} onChange={event=>onChange('text',event.target.value)} className="ui-field" placeholder="Например тераса" /></div>
      </div></details>
    </div><button type="submit" className="ui-button mt-6 w-full">Покажи обяви</button>
  </form>;
}
